app:
  name: nexa
  version: 1.0
  organization_mode: true
  default_language: en

agents:
  enabled:
    - master
    - booking
    - hr
    - safety

logging:
  level: INFO
  filepath: logs/nexa.log
